/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.RetailManagerWorkArea;

import ui.SupplierPricingAnalystRole.*;
import Business.EcoSystem;
import Business.Organization.Organization;
import Business.Organization.RetailStoreOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ManufacturingQuotesRequest;
import Business.WorkQueue.StoreAssociateToStoreMRestockRequest;
import Business.WorkQueue.StoreManagerToStoreARestockRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.GridLayout;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class ManagerToAssociateRequest extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
   private RetailStoreOrganization retailStoreOrganization;
    
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public ManagerToAssociateRequest(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.retailStoreOrganization = (RetailStoreOrganization) organization;
        populateTable();
      
    }
  private void populateTable() {

 DefaultTableModel model = (DefaultTableModel) workRequestJTable1.getModel();
        model.setRowCount(0);

        // Filter for StoreAssociateToStoreMRestockRequest (from associates to manager)
        for (WorkRequest wr : retailStoreOrganization.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof StoreAssociateToStoreMRestockRequest) {
                StoreAssociateToStoreMRestockRequest req = (StoreAssociateToStoreMRestockRequest) wr;
                Object[] row = new Object[4];
                row[0] = req; // toString() will display the message
                row[1] = req.getStatus();
                model.addRow(row);
            }
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refreshJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        workRequestJTable1 = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnDeny = new javax.swing.JButton();
        btnApprove = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("Messages from Store Associates");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        workRequestJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Message", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(workRequestJTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 630, 340));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnDeny.setText("Deny");
        btnDeny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDenyActionPerformed(evt);
            }
        });
        add(btnDeny, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, -1, -1));

        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });
        add(btnApprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
     populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDenyActionPerformed
        // TODO add your handling code here:
  int selectedRow = workRequestJTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a request to confirm.");
            return;
        }

        WorkRequest wr = (WorkRequest) workRequestJTable1.getValueAt(selectedRow, 0);
        if (!(wr instanceof StoreAssociateToStoreMRestockRequest)) {
            JOptionPane.showMessageDialog(this, "Invalid request type for confirmation.");
            return;
        }

        // Process / Confirm the restock request
        StoreAssociateToStoreMRestockRequest req = (StoreAssociateToStoreMRestockRequest) wr;
        req.setReceiver(userAccount);      // Manager assigns themselves as receiver
        req.setStatus("Denied");         // Manager denies the associate's request

        JOptionPane.showMessageDialog(this, "Restock request from associate denied.");
        populateTable(); // Refresh table to show new status

    }//GEN-LAST:event_btnDenyActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
        int selectedRow = workRequestJTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a request to confirm.");
            return;
        }

        WorkRequest wr = (WorkRequest) workRequestJTable1.getValueAt(selectedRow, 0);
        if (!(wr instanceof StoreAssociateToStoreMRestockRequest)) {
            JOptionPane.showMessageDialog(this, "Invalid request type for confirmation.");
            return;
        }

        // Process / Confirm the restock request
        StoreAssociateToStoreMRestockRequest req = (StoreAssociateToStoreMRestockRequest) wr;
        req.setReceiver(userAccount);      // Manager assigns themselves as receiver
        req.setStatus("Approved");         // Manager confirms the associate's request

        JOptionPane.showMessageDialog(this, "Restock request from associate confirmed.");
        populateTable(); // Refresh table to show new status
    }//GEN-LAST:event_btnApproveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeny;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JTable workRequestJTable1;
    // End of variables declaration//GEN-END:variables
}
