/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SupplierDataAnalystWorkArea;

import ui.SupplierPricingAnalystRole.*;
import ui.SupplierPricingAnalystRole.*;
import Business.EcoSystem;
import Business.Organization.SupplierPricingOrganization;
import Business.Organization.Organization;
import Business.Organization.SupplierDataAnalyticsOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ManufacturingQuotesRequest;
import Business.WorkQueue.MarketingRequest;
import Business.WorkQueue.PriceChangeRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class SupplierDataAnalystMarketingRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private SupplierDataAnalyticsOrganization supplierDataAnalyticsOrganization;
    
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public SupplierDataAnalystMarketingRequestJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.supplierDataAnalyticsOrganization = (SupplierDataAnalyticsOrganization) organization;
        populateTable();
       
    }
    
     private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable2.getModel();
        model.setRowCount(0);

        for (WorkRequest wr : supplierDataAnalyticsOrganization.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof MarketingRequest) {
                Object[] row = new Object[2];
                row[0] = wr;                                 // will call toString() on PriceChangeRequest
                row[1] = wr.getStatus();
                model.addRow(row);
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refreshJButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        workRequestJTable2 = new javax.swing.JTable();
        btnRequestMarketing = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        refreshJButton2.setText("Refresh");
        refreshJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButton2ActionPerformed(evt);
            }
        });
        add(refreshJButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setText("Messages for Marketer");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        workRequestJTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Message", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(workRequestJTable2);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 530, 260));

        btnRequestMarketing.setText("Request Marketing Strategy");
        btnRequestMarketing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestMarketingActionPerformed(evt);
            }
        });
        add(btnRequestMarketing, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButton2ActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_refreshJButton2ActionPerformed

    private void btnRequestMarketingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestMarketingActionPerformed
        // TODO add your handling code here:
         // Prompt the analyst for a description of the price change
        String msg = JOptionPane.showInputDialog(
                this,
                "Enter marketing request details",
                "Request",
                JOptionPane.PLAIN_MESSAGE
        );

        if (msg == null) {
            // user cancelled
            return;
        }
        msg = msg.trim();
        if (msg.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a message.");
            return;
        }

        // Create and send the request
        MarketingRequest request = new MarketingRequest();
        request.setMessage(msg);        // base WorkRequest message
        request.setTestResult(msg);     // reuse your existing field if needed
        request.setSender(userAccount);
        request.setStatus("Sent");

        // Add to Supplier Pricing org queue and (optionally) to sender's queue
        supplierDataAnalyticsOrganization.getWorkQueue().getWorkRequestList().add(request);
        userAccount.getWorkQueue().getWorkRequestList().add(request);

        JOptionPane.showMessageDialog(this, "Marketing request sent");
        populateTable();

    }//GEN-LAST:event_btnRequestMarketingActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequestMarketing;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton refreshJButton2;
    private javax.swing.JTable workRequestJTable2;
    // End of variables declaration//GEN-END:variables
}
