/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SupplierDataAnalystWorkArea;

import ui.SupplierPricingAnalystRole.SupplierPAToManufacturePA;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author lajon
 */
public class SupplierDataAnalystMenuJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private Organization organization;
    
    /**
     * Creates new form RetailDataAnalystMenuJPanel
     */
   public SupplierDataAnalystMenuJPanel() {
        this(null, null, null, null);
    }

    
    public SupplierDataAnalystMenuJPanel(JPanel userProcessContainer,
                                       UserAccount account,
                                       Organization organization,
                                       EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.business = business;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDataRequestManufacturer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSalesData = new javax.swing.JButton();
        btnDataRequestPricing = new javax.swing.JButton();

        btnDataRequestManufacturer.setBackground(new java.awt.Color(102, 153, 255));
        btnDataRequestManufacturer.setForeground(new java.awt.Color(255, 255, 255));
        btnDataRequestManufacturer.setText("Make Marketing Request");
        btnDataRequestManufacturer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDataRequestManufacturer.setMaximumSize(new java.awt.Dimension(145, 40));
        btnDataRequestManufacturer.setMinimumSize(new java.awt.Dimension(20, 20));
        btnDataRequestManufacturer.setPreferredSize(new java.awt.Dimension(240, 25));
        btnDataRequestManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataRequestManufacturerIdentifyEventsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Retail Data Analyst Menu");

        btnSalesData.setBackground(new java.awt.Color(102, 153, 255));
        btnSalesData.setForeground(new java.awt.Color(255, 255, 255));
        btnSalesData.setText("View Sales Data ");
        btnSalesData.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalesData.setMaximumSize(new java.awt.Dimension(200, 40));
        btnSalesData.setMinimumSize(new java.awt.Dimension(20, 23));
        btnSalesData.setPreferredSize(new java.awt.Dimension(240, 30));
        btnSalesData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesDataIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnDataRequestPricing.setBackground(new java.awt.Color(102, 153, 255));
        btnDataRequestPricing.setForeground(new java.awt.Color(255, 255, 255));
        btnDataRequestPricing.setText("Request Pricing Change");
        btnDataRequestPricing.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDataRequestPricing.setMaximumSize(new java.awt.Dimension(200, 40));
        btnDataRequestPricing.setMinimumSize(new java.awt.Dimension(20, 20));
        btnDataRequestPricing.setPreferredSize(new java.awt.Dimension(240, 25));
        btnDataRequestPricing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataRequestPricingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalesData, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(btnDataRequestPricing, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btnDataRequestManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalesData, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDataRequestPricing, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnDataRequestManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDataRequestManufacturerIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataRequestManufacturerIdentifyEventsActionPerformed
        // TODO add your handling code here:
          if (userProcessContainer == null) {
        return;
    }
    
    // Go to the panel that lets analyst make manufacturer & pricing requests
    SupplierDataAnalystMarketingRequestJPanel panel =
        new SupplierDataAnalystMarketingRequestJPanel(
            userProcessContainer,
            userAccount,
            organization,
            business
        );

    userProcessContainer.add("RetailDataAnalystMarketingRequestJPanel", panel);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);
    }//GEN-LAST:event_btnDataRequestManufacturerIdentifyEventsActionPerformed

    private void btnSalesDataIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesDataIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        Enterprise targetEnterprise = business.getNetworkList().get(0).getEnterpriseDirectory().getEnterpriseList().stream().filter(e -> e.getName().equals("Nike")).findFirst().orElse(null);
        for (Organization org : targetEnterprise.getOrganizationDirectory().getOrganizationList()) {
            System.out.println("Checking org: " + org.getName()); // DEBUG

            if (org.getName().equalsIgnoreCase("Retail Data Analytics Organization")) {
                Organization targetOrg = org;
                SupplierDataAnalystOrdersJPanel retailDataAnalystInventoryJPanel
                    = new SupplierDataAnalystOrdersJPanel(
                        userProcessContainer          
                        ,userAccount,
                        org,
                        business,
                        targetEnterprise
                    );

            userProcessContainer.add(
                "RetailDataAnalystInventoryJPanel",
                retailDataAnalystInventoryJPanel
            );

            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
            }
        }
    }//GEN-LAST:event_btnSalesDataIdentifyResourceAssetsActionPerformed

    private void btnDataRequestPricingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataRequestPricingActionPerformed
        // TODO add your handling code here:
 if (userProcessContainer == null) {
        return;
    }
    Enterprise targetEnterprise = business.getNetworkList().get(0).getEnterpriseDirectory().getEnterpriseList().stream().filter(e -> e.getName().equals("Nike")).findFirst().orElse(null);
    for (Organization org : targetEnterprise.getOrganizationDirectory().getOrganizationList()) {
        System.out.println("Checking org: " + org.getName()); // DEBUG

        if (org.getName().equalsIgnoreCase("Supplier Pricing Organization")) {
            Organization targetOrg = org;
            SupplierDataAnalystPricingRequestJPanel retailDataAnalystPricingRequestJPanel =
            new SupplierDataAnalystPricingRequestJPanel(
            userProcessContainer,
            userAccount,
            targetOrg,
            business
            );

            userProcessContainer.add("RetailDataAnalystPricingRequestJPanel",retailDataAnalystPricingRequestJPanel );
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);

            }
        }
    }//GEN-LAST:event_btnDataRequestPricingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDataRequestManufacturer;
    private javax.swing.JButton btnDataRequestPricing;
    private javax.swing.JButton btnSalesData;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
