/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.StoreAssociateWorkArea;

import java.awt.CardLayout;
import ui.RetailBusinessAnalystWorkArea.RetailBusinessAnalystWorkAreaJPanel;
import Business.EcoSystem;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author lajon
 */
public class StoreAssociateMenuJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private Organization organization;
    /**
     * Creates new form StoreAssociateMenuJPanel
     */
    public StoreAssociateMenuJPanel() {
        this(null, null, null, null);
    }

    // Real constructor used from Role.createWorkArea(...)
    public StoreAssociateMenuJPanel(JPanel userProcessContainer,
                                    UserAccount account,
                                    Organization organization,
                                    EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.business = business;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnStoreAssociateRequestManager = new javax.swing.JButton();
        btnStoreAssociateViewInventory = new javax.swing.JButton();
        btnStoreAssociateViewInventory1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Store Associate Menu");

        btnStoreAssociateRequestManager.setBackground(new java.awt.Color(102, 153, 255));
        btnStoreAssociateRequestManager.setForeground(new java.awt.Color(255, 255, 255));
        btnStoreAssociateRequestManager.setText("Request Manager");
        btnStoreAssociateRequestManager.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStoreAssociateRequestManager.setMaximumSize(new java.awt.Dimension(200, 40));
        btnStoreAssociateRequestManager.setMinimumSize(new java.awt.Dimension(20, 23));
        btnStoreAssociateRequestManager.setPreferredSize(new java.awt.Dimension(240, 30));
        btnStoreAssociateRequestManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStoreAssociateRequestManagerIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnStoreAssociateViewInventory.setBackground(new java.awt.Color(102, 153, 255));
        btnStoreAssociateViewInventory.setForeground(new java.awt.Color(255, 255, 255));
        btnStoreAssociateViewInventory.setText("View Inventory");
        btnStoreAssociateViewInventory.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStoreAssociateViewInventory.setMaximumSize(new java.awt.Dimension(200, 40));
        btnStoreAssociateViewInventory.setMinimumSize(new java.awt.Dimension(20, 23));
        btnStoreAssociateViewInventory.setPreferredSize(new java.awt.Dimension(240, 30));
        btnStoreAssociateViewInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStoreAssociateViewInventoryIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnStoreAssociateViewInventory1.setBackground(new java.awt.Color(102, 153, 255));
        btnStoreAssociateViewInventory1.setForeground(new java.awt.Color(255, 255, 255));
        btnStoreAssociateViewInventory1.setText("Sell Products");
        btnStoreAssociateViewInventory1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStoreAssociateViewInventory1.setMaximumSize(new java.awt.Dimension(200, 40));
        btnStoreAssociateViewInventory1.setMinimumSize(new java.awt.Dimension(20, 23));
        btnStoreAssociateViewInventory1.setPreferredSize(new java.awt.Dimension(240, 30));
        btnStoreAssociateViewInventory1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStoreAssociateViewInventory1IdentifyResourceAssetsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStoreAssociateViewInventory1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnStoreAssociateViewInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStoreAssociateRequestManager, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStoreAssociateViewInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStoreAssociateRequestManager, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnStoreAssociateViewInventory1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(236, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStoreAssociateRequestManagerIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStoreAssociateRequestManagerIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
if (userProcessContainer == null) {
        return;
    }

    // Open StoreAssociate work area (inventory + manager messages + request restock)
    StoreAssociateWorkAreaJPanel workAreaPanel =
        new StoreAssociateWorkAreaJPanel(
            userProcessContainer,
            userAccount,
            organization,
            business
        );

    userProcessContainer.add("StoreAssociateWorkAreaJPanel", workAreaPanel);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);

    }//GEN-LAST:event_btnStoreAssociateRequestManagerIdentifyResourceAssetsActionPerformed

    private void btnStoreAssociateViewInventoryIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStoreAssociateViewInventoryIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
     if (userProcessContainer == null) {
        return;
    }

    // Same work area also shows inventory; you can reuse it
    StoreAssociateInventoryJPanel storeAssociateInventoryJPanel =
        new StoreAssociateInventoryJPanel(
            userProcessContainer,
            userAccount,
            organization,
            business
        );

    userProcessContainer.add("StoreAssociateInventoryJPanel", storeAssociateInventoryJPanel);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);
   

    }//GEN-LAST:event_btnStoreAssociateViewInventoryIdentifyResourceAssetsActionPerformed

    private void btnStoreAssociateViewInventory1IdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStoreAssociateViewInventory1IdentifyResourceAssetsActionPerformed
        System.out.println("=== BUTTON CLICKED ===");
        if (userProcessContainer == null) {
        return;
    }

    // Same work area also shows inventory; you can reuse it
    SellRetailProductsJPanel sellRetailProductsJPanel =
        new SellRetailProductsJPanel(
            userProcessContainer,
            business
        );

    userProcessContainer.add("SellRetailProductsJPanel", sellRetailProductsJPanel);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.show(userProcessContainer,"SellRetailProductsJPanel");
   

    }//GEN-LAST:event_btnStoreAssociateViewInventory1IdentifyResourceAssetsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStoreAssociateRequestManager;
    private javax.swing.JButton btnStoreAssociateViewInventory;
    private javax.swing.JButton btnStoreAssociateViewInventory1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
