/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ShippingPricingAnalystWorkArea;
import Business.EcoSystem;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author lajon
 */
public class ShippingTotalCostJPanel extends javax.swing.JPanel {
 private static final long serialVersionUID = 1L;

 private JPanel userProcessContainer;
 private UserAccount userAccount;
 private Organization organization;
 private EcoSystem business;
    /**
     * Creates new form ShippingTotalCostJPanel
     */
   
  public ShippingTotalCostJPanel() {
 initComponents();
 }
  
 public ShippingTotalCostJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, EcoSystem business) {
 this.userProcessContainer = userProcessContainer;
 this.userAccount = userAccount;
 this.organization = organization;
 this.business = business;
 initComponents();
 // existing populate or setup methods can be called elsewhere as needed
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}