/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ShippingPricingAnalystWorkArea;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author lajon
 */
public class ShippingPricingAnalystMenuJPanel extends javax.swing.JPanel {

 private static final long serialVersionUID = 1L;

 private JPanel userProcessContainer;
 private UserAccount userAccount;
 private Organization organization;
 private EcoSystem business;

    /**
     * Creates new form ShippingPricingAnalystMenuJPanel
     */
   
 public ShippingPricingAnalystMenuJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, EcoSystem business) {
 initComponents();
 this.userProcessContainer = userProcessContainer;
 this.userAccount = userAccount;
 this.organization = organization;
 this.business = business;
 }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnApprovedQuotes = new javax.swing.JButton();
        btnMessagesfromSupplierPA = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Shipping Pricing Analyst Menu");

        btnApprovedQuotes.setBackground(new java.awt.Color(102, 153, 255));
        btnApprovedQuotes.setForeground(new java.awt.Color(255, 255, 255));
        btnApprovedQuotes.setText("Approved Quotes");
        btnApprovedQuotes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnApprovedQuotes.setMaximumSize(new java.awt.Dimension(200, 40));
        btnApprovedQuotes.setMinimumSize(new java.awt.Dimension(20, 23));
        btnApprovedQuotes.setPreferredSize(new java.awt.Dimension(240, 30));
        btnApprovedQuotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApprovedQuotesIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnMessagesfromSupplierPA.setBackground(new java.awt.Color(102, 153, 255));
        btnMessagesfromSupplierPA.setForeground(new java.awt.Color(255, 255, 255));
        btnMessagesfromSupplierPA.setText("Messages from Supplier Pricing Analyst");
        btnMessagesfromSupplierPA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMessagesfromSupplierPA.setMaximumSize(new java.awt.Dimension(200, 40));
        btnMessagesfromSupplierPA.setMinimumSize(new java.awt.Dimension(20, 20));
        btnMessagesfromSupplierPA.setPreferredSize(new java.awt.Dimension(240, 25));
        btnMessagesfromSupplierPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMessagesfromSupplierPAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnApprovedQuotes, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btnMessagesfromSupplierPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApprovedQuotes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMessagesfromSupplierPA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(313, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnApprovedQuotesIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApprovedQuotesIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
      if (userProcessContainer == null) {
            return;
        }

        ShippingApprovedQuotesJPanel shippingTotalCostJPanel =
        new ShippingApprovedQuotesJPanel(
            userProcessContainer,
            userAccount,
            organization,
            business
        );

        userProcessContainer.add("ShippingTotalCostJPanel", shippingTotalCostJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);  
    }//GEN-LAST:event_btnApprovedQuotesIdentifyResourceAssetsActionPerformed

    private void btnMessagesfromSupplierPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMessagesfromSupplierPAActionPerformed
        // TODO add your handling code here:
        Organization targetOrg = null;
        Enterprise targetEnterprise = business.getNetworkList().get(0).getEnterpriseDirectory().getEnterpriseList().stream().filter(e -> e.getName().equals("Nike")).findFirst().orElse(null);
        for (Organization org : targetEnterprise.getOrganizationDirectory().getOrganizationList()) {
            System.out.println("Checking org: " + org.getName()); // DEBUG

            if (org.getName().equalsIgnoreCase("Supplier Pricing Organization")) {
                targetOrg = org;
            }
            if (userProcessContainer == null) {
            return;
            }
        }

            ShippingContactSupplierJPanel shippingContactSupplierJPanel =
            new ShippingContactSupplierJPanel(
            userProcessContainer,
            userAccount,
            targetOrg,
            business
        );
        

        userProcessContainer.add("ShippingContactSupplierJPanel", shippingContactSupplierJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnMessagesfromSupplierPAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprovedQuotes;
    private javax.swing.JButton btnMessagesfromSupplierPA;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
