/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ShippingPricingAnalystWorkArea;
import Business.EcoSystem;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JPanel;
import Business.Organization.SupplierPricingOrganization;
import Business.WorkQueue.ShippingQuotesRequest;
import Business.Network.Network;
import javax.swing.table.DefaultTableModel;
import Business.Enterprise.Enterprise; 


/**
 *
 * @author lajon
 */
public class ShippingContactSupplierJPanel extends javax.swing.JPanel {
 private static final long serialVersionUID = 1L;

 private JPanel userProcessContainer;
 private UserAccount userAccount;
 private Organization organization;
 private EcoSystem business;
    /**
     * Creates new form ShippingTotalCostJPanel
     */
   
  public ShippingContactSupplierJPanel() {
 initComponents();
 }
  
 public ShippingContactSupplierJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, EcoSystem business) {
 this.userProcessContainer = userProcessContainer;
 this.userAccount = userAccount;
 this.organization = organization;
 this.business = business;
 initComponents();
 populateTable();
 // existing populate or setup methods can be called elsewhere as needed
 }
private void populateTable() {
    DefaultTableModel m = (DefaultTableModel) workRequestJTable1.getModel();
    m.setRowCount(0);
    for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()) {
        if (wr instanceof ShippingQuotesRequest) {
            m.addRow(new Object[]{
                wr,                                        // message/toString
                wr.getSender() == null ? null : wr.getSender().getEmployee().getName(),
                wr.getReceiver() == null ? null : wr.getReceiver().getEmployee().getName(),
                wr.getStatus()
            });
        }
    }
}
   

private Organization findSupplierPricingOrg() {
    if (business == null) return null;
    for (Network net : business.getNetworkList()) {
        for (Enterprise ent : net.getEnterpriseDirectory().getEnterpriseList()) {
            // optionally restrict to supplier enterprise:
            // if (ent.getEnterpriseType() != Enterprise.EnterpriseType.SUPPLIER) continue;
            for (Organization org : ent.getOrganizationDirectory().getOrganizationList()) {
                if (org instanceof SupplierPricingOrganization) {
                    return org;
                }
            }
        }
    }
    return null;
}/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refreshJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        workRequestJTable1 = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        assignJButton1 = new javax.swing.JButton();

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("Messages from Supplier Pricing Analyst");

        workRequestJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Receiver", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(workRequestJTable1);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        assignJButton1.setText("New Message");
        assignJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(assignJButton1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(refreshJButton))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(refreshJButton))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(assignJButton1)
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
     populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void assignJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButton1ActionPerformed
        // TODO add your handling code here:
          String msg = javax.swing.JOptionPane.showInputDialog(
        this,
        "Enter quote details (items + total price):",
        "New Shipping Quote",
        javax.swing.JOptionPane.PLAIN_MESSAGE
    );
    if (msg == null) return;
    msg = msg.trim();
    if (msg.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter a message.");
        return;
    }
    
    Organization supplierPricingOrg = findSupplierPricingOrg();
if (supplierPricingOrg == null) {
    javax.swing.JOptionPane.showMessageDialog(this, "No Supplier Pricing Organization found.");
    return;
}

ShippingQuotesRequest req = new ShippingQuotesRequest();
req.setMessage(msg);
req.setTestResult(msg);      // keep your field in sync
req.setSender(userAccount);
req.setStatus("Sent");

// Send to Supplier Pricing org
supplierPricingOrg.getWorkQueue().getWorkRequestList().add(req);
// Optional: keep a copy in shipping analyst’s queue
userAccount.getWorkQueue().getWorkRequestList().add(req);
// Optional: also reflect in this (shipping) org’s queue so it lists locally
organization.getWorkQueue().getWorkRequestList().add(req);

javax.swing.JOptionPane.showMessageDialog(this, "Quote sent to Supplier Pricing Analyst.");
populateTable();
    }//GEN-LAST:event_assignJButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton1;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JTable workRequestJTable1;
    // End of variables declaration//GEN-END:variables

}