/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ShippingPricingAnalystWorkArea;
import Business.EcoSystem;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author lajon
 */
public class ShippingPricingAnalystMenuJPanel extends javax.swing.JPanel {

 private static final long serialVersionUID = 1L;

 private JPanel userProcessContainer;
 private UserAccount userAccount;
 private Organization organization;
 private EcoSystem business;

    /**
     * Creates new form ShippingPricingAnalystMenuJPanel
     */
   
 public ShippingPricingAnalystMenuJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, EcoSystem business) {
 initComponents();
 this.userProcessContainer = userProcessContainer;
 this.userAccount = userAccount;
 this.organization = organization;
 this.business = business;
 }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCreateViewApprovedQuotes = new javax.swing.JButton();
        btnTotalShippingCost = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Shipping Pricing Analyst Menu");

        btnCreateViewApprovedQuotes.setBackground(new java.awt.Color(102, 153, 255));
        btnCreateViewApprovedQuotes.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateViewApprovedQuotes.setText("Create and View Quotes");
        btnCreateViewApprovedQuotes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCreateViewApprovedQuotes.setMaximumSize(new java.awt.Dimension(200, 40));
        btnCreateViewApprovedQuotes.setMinimumSize(new java.awt.Dimension(20, 23));
        btnCreateViewApprovedQuotes.setPreferredSize(new java.awt.Dimension(240, 30));
        btnCreateViewApprovedQuotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateViewApprovedQuotesIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnTotalShippingCost.setBackground(new java.awt.Color(102, 153, 255));
        btnTotalShippingCost.setForeground(new java.awt.Color(255, 255, 255));
        btnTotalShippingCost.setText("Total Shipping Cost");
        btnTotalShippingCost.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTotalShippingCost.setMaximumSize(new java.awt.Dimension(200, 40));
        btnTotalShippingCost.setMinimumSize(new java.awt.Dimension(20, 20));
        btnTotalShippingCost.setPreferredSize(new java.awt.Dimension(240, 25));
        btnTotalShippingCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalShippingCostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreateViewApprovedQuotes, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btnTotalShippingCost, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateViewApprovedQuotes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTotalShippingCost, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(313, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateViewApprovedQuotesIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateViewApprovedQuotesIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        if (userProcessContainer == null) {
            return;
        }

        ShippingPricingAnalystWorkAreaJPanel shippingPricingAnalystWorkAreaJPanel  =
        new ShippingPricingAnalystWorkAreaJPanel(
            userProcessContainer,
            userAccount,
            organization,
            business
        );

        userProcessContainer.add("ShippingPricingAnalystWorkAreaJPanel", shippingPricingAnalystWorkAreaJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateViewApprovedQuotesIdentifyResourceAssetsActionPerformed

    private void btnTotalShippingCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalShippingCostActionPerformed
        // TODO add your handling code here:
        if (userProcessContainer == null) {
            return;
        }

        ShippingApprovedQuotesJPanel shippingTotalCostJPanel =
        new ShippingApprovedQuotesJPanel(
            userProcessContainer,
            userAccount,
            organization,
            business
        );

        userProcessContainer.add("ShippingTotalCostJPanel", shippingTotalCostJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnTotalShippingCostActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateViewApprovedQuotes;
    private javax.swing.JButton btnTotalShippingCost;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
