/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SupplierMarketingSpecialistWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import ui.SupplierPricingAnalystRole.SupplierPAToManufacturePA;

/**
 *
 * @author lajon
 */
public class MarketingMenuJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private Organization organization;

    /**
     * Creates new form RetailMarketingSpecialistMenuJPanel
     */
      public MarketingMenuJPanel() {
        this(null, null, null, null);
    }

    public MarketingMenuJPanel(JPanel userProcessContainer,
                                               UserAccount account,
                                               Organization organization,
                                               EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnMarketingViewInventory = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Retail Marketing Specialist Menu");

        btnMarketingViewInventory.setBackground(new java.awt.Color(102, 153, 255));
        btnMarketingViewInventory.setForeground(new java.awt.Color(255, 255, 255));
        btnMarketingViewInventory.setText("Marketing Requests");
        btnMarketingViewInventory.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMarketingViewInventory.setMaximumSize(new java.awt.Dimension(200, 40));
        btnMarketingViewInventory.setMinimumSize(new java.awt.Dimension(20, 23));
        btnMarketingViewInventory.setPreferredSize(new java.awt.Dimension(240, 30));
        btnMarketingViewInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarketingViewInventoryIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMarketingViewInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(btnMarketingViewInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(350, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMarketingViewInventoryIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarketingViewInventoryIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        Organization targetOrg = null;
    
        Enterprise targetEnterprise = business.getNetworkList().get(0).getEnterpriseDirectory().getEnterpriseList().stream().filter(e -> e.getName().equals("Nike")).findFirst().orElse(null);
        for (Organization org : targetEnterprise.getOrganizationDirectory().getOrganizationList()) {
            System.out.println("Checking org: " + org.getName()); // DEBUG

            if (org.getName().equalsIgnoreCase("Supplier Data Analytics Organization")) {
                targetOrg = org;
                
            }
            if (userProcessContainer == null) {
            return;
            }
        }
    MarketingRequestsJPanel marketingRequestsJPanel =
            new MarketingRequestsJPanel(
                userProcessContainer,
                userAccount,
                targetOrg,
                business
            );

        userProcessContainer.add("MarketingRequestsJPanel",marketingRequestsJPanel );
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
    }//GEN-LAST:event_btnMarketingViewInventoryIdentifyResourceAssetsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMarketingViewInventory;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
