/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.ManufacturingProductionPlannerWorkArea;

import ui.SupplierPricingAnalystRole.*;
import ui.SupplierPricingAnalystRole.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.ManufacturingOperationsOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ManufacturingQuotesRequest;
import Business.WorkQueue.ProductionMaterialsRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class ProductionPlannerWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private ManufacturingOperationsOrganization manufacturingOperationsOrganization;
    private  Organization organization;

    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public ProductionPlannerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business, Enterprise enterprise) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.manufacturingOperationsOrganization = (ManufacturingOperationsOrganization) organization;
        this.organization = organization;
        this.enterprise = enterprise;

        populateTable();
    }

    private void populateTable() {
    DefaultTableModel m = new DefaultTableModel(new Object[][]{}, new String[] {"Message","Status"}) {
        public boolean isCellEditable(int r,int c){ return false; }
    };
    workRequestJTable1.setModel(m);
    for (WorkRequest wr : enterprise.getWorkQueue().getWorkRequestList()) {
        if (wr instanceof ProductionMaterialsRequest) {
            m.addRow(new Object[]{
                wr,
                wr.getStatus()
            });
        }
    }
}
    
    private Organization findTargetOrg(Class<?> cls) {
    if (business == null) return null;
    for (Network net : business.getNetworkList()) {
        for (Enterprise ent : net.getEnterpriseDirectory().getEnterpriseList()) {
            for (Organization org : ent.getOrganizationDirectory().getOrganizationList()) {
                if (cls.isInstance(org)) return org;
            }
        }
    }
    return null;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        workRequestJTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        refreshJButton3 = new javax.swing.JButton();
        refreshJButton4 = new javax.swing.JButton();
        refreshJButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workRequestJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Production Change", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(workRequestJTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 670, 440));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setText("Items in Production");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        refreshJButton3.setText("Refresh");
        refreshJButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButton3ActionPerformed(evt);
            }
        });
        add(refreshJButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, -1, -1));

        refreshJButton4.setText("Provide Change Verdict");
        refreshJButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButton4ActionPerformed(evt);
            }
        });
        add(refreshJButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, -1, -1));

        refreshJButton2.setText("<<< Back");
        refreshJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButton2ActionPerformed(evt);
            }
        });
        add(refreshJButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshJButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButton3ActionPerformed
        // TODO add your handling code here:
         populateTable();
    }//GEN-LAST:event_refreshJButton3ActionPerformed

    private void refreshJButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButton4ActionPerformed
      int selectedRow = workRequestJTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a request.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) workRequestJTable1.getModel();
        ProductionMaterialsRequest request
                = (ProductionMaterialsRequest) model.getValueAt(selectedRow, 0);

        String verdict = JOptionPane.showInputDialog(
                this,
                "Enter Verdict (Approve / Deny):",
                "Restock Decision",
                JOptionPane.PLAIN_MESSAGE
        );

        if (verdict == null || verdict.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Verdict cannot be empty.");
            return;
        }

        verdict = verdict.trim();

// Set ONLY status
        request.setStatus(
                verdict.equalsIgnoreCase("Approve") ? "Approved" : "Denied"
        );

// do NOT touch message
        JOptionPane.showMessageDialog(this,
                "Decision recorded: " + request.getStatus()
        );

        populateTable();
    }//GEN-LAST:event_refreshJButton4ActionPerformed

    private void refreshJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButton2ActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshJButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshJButton2;
    private javax.swing.JButton refreshJButton3;
    private javax.swing.JButton refreshJButton4;
    private javax.swing.JTable workRequestJTable1;
    // End of variables declaration//GEN-END:variables
}
