/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ManufacturingPricingAnalystWorkArea;
import Business.EcoSystem;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author lajon
 */
public class ManufacturingPricingAnalystMenuJPanel extends javax.swing.JPanel {
 private static final long serialVersionUID = 1L;

 private JPanel userProcessContainer;
 private UserAccount userAccount;
 private Organization organization;
 private EcoSystem business;
    /**
     * Creates new form ManufacturingPricingAnalystMenuJPanel
     */
 public ManufacturingPricingAnalystMenuJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, EcoSystem business) {
 initComponents();
 this.userProcessContainer = userProcessContainer;
 this.userAccount = userAccount;
 this.organization = organization;
 this.business = business;
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnViewProducts = new javax.swing.JButton();
        btnSendQuotes = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Manufacturing Pricing Analyst Menu");

        btnViewProducts.setBackground(new java.awt.Color(102, 153, 255));
        btnViewProducts.setForeground(new java.awt.Color(255, 255, 255));
        btnViewProducts.setText("View Products ");
        btnViewProducts.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewProducts.setMaximumSize(new java.awt.Dimension(200, 40));
        btnViewProducts.setMinimumSize(new java.awt.Dimension(20, 23));
        btnViewProducts.setPreferredSize(new java.awt.Dimension(240, 30));
        btnViewProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProductsIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnSendQuotes.setBackground(new java.awt.Color(102, 153, 255));
        btnSendQuotes.setForeground(new java.awt.Color(255, 255, 255));
        btnSendQuotes.setText("Send Quotes");
        btnSendQuotes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSendQuotes.setMaximumSize(new java.awt.Dimension(200, 40));
        btnSendQuotes.setMinimumSize(new java.awt.Dimension(20, 20));
        btnSendQuotes.setPreferredSize(new java.awt.Dimension(240, 25));
        btnSendQuotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendQuotesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnViewProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btnSendQuotes, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendQuotes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(312, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewProductsIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProductsIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
       if (userProcessContainer == null) {
     return;
 }

 ManufacturingPricingAnalystWorkAreaJPanel manufacturingPricingAnalystWorkAreaJPanel =
     new ManufacturingPricingAnalystWorkAreaJPanel(
         userProcessContainer,
         userAccount,
         organization,
         business
     );

 userProcessContainer.add("ManufacturingPricingAnalystWorkAreaJPanel", manufacturingPricingAnalystWorkAreaJPanel);
 CardLayout layout = (CardLayout) userProcessContainer.getLayout();
 layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewProductsIdentifyResourceAssetsActionPerformed

    private void btnSendQuotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendQuotesActionPerformed
        // TODO add your handling code here:
    if (userProcessContainer == null) {
     return;
    }

    ManufacturingPricingAnalystSendQuotesJPanel manufacturingPricingAnalystSendQuotesJPanel =
     new ManufacturingPricingAnalystSendQuotesJPanel(
         userProcessContainer,
         userAccount,
         organization,
         business
     );

    userProcessContainer.add("ManufacturingPricingAnalystSendQuotesJPanel", manufacturingPricingAnalystSendQuotesJPanel);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);

    }//GEN-LAST:event_btnSendQuotesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendQuotes;
    private javax.swing.JButton btnViewProducts;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
