/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ManufacturingPricingAnalystWorkArea;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author lajon
 */
public class ManufacturingPricingAnalystMenuJPanel extends javax.swing.JPanel {
 private static final long serialVersionUID = 1L;

 private JPanel userProcessContainer;
 private UserAccount userAccount;
 private Organization organization;
 private EcoSystem business;
 private Enterprise enterprise;
    /**
     * Creates new form ManufacturingPricingAnalystMenuJPanel
     */
 public ManufacturingPricingAnalystMenuJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, EcoSystem business, Enterprise enterprise) {
 initComponents();
 this.userProcessContainer = userProcessContainer;
 this.userAccount = userAccount;
 this.organization = organization;
 this.business = business;
 this.enterprise = enterprise;
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSendQuotes = new javax.swing.JButton();
        btnRequestChangeProduction = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Manufacturing Pricing Analyst Menu");

        btnSendQuotes.setBackground(new java.awt.Color(102, 153, 255));
        btnSendQuotes.setForeground(new java.awt.Color(255, 255, 255));
        btnSendQuotes.setText("Send Quotes");
        btnSendQuotes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSendQuotes.setMaximumSize(new java.awt.Dimension(200, 40));
        btnSendQuotes.setMinimumSize(new java.awt.Dimension(20, 20));
        btnSendQuotes.setPreferredSize(new java.awt.Dimension(240, 25));
        btnSendQuotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendQuotesActionPerformed(evt);
            }
        });

        btnRequestChangeProduction.setBackground(new java.awt.Color(102, 153, 255));
        btnRequestChangeProduction.setForeground(new java.awt.Color(255, 255, 255));
        btnRequestChangeProduction.setText("Make Request to Change Production");
        btnRequestChangeProduction.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRequestChangeProduction.setMaximumSize(new java.awt.Dimension(200, 40));
        btnRequestChangeProduction.setMinimumSize(new java.awt.Dimension(20, 20));
        btnRequestChangeProduction.setPreferredSize(new java.awt.Dimension(240, 25));
        btnRequestChangeProduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestChangeProductionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnSendQuotes, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(btnRequestChangeProduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSendQuotes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRequestChangeProduction, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(308, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendQuotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendQuotesActionPerformed
        // TODO add your handling code here:
        Organization targetOrg = null;
    
        Enterprise targetEnterprise = business.getNetworkList().get(0).getEnterpriseDirectory().getEnterpriseList().stream().filter(e -> e.getName().equals("Nike")).findFirst().orElse(null);
        for (Organization org : targetEnterprise.getOrganizationDirectory().getOrganizationList()) {
            System.out.println("Checking org: " + org.getName()); // DEBUG

            if (org.getName().equalsIgnoreCase("Supplier Pricing Organization")) {
                targetOrg = org;
                
            }
            if (userProcessContainer == null) {
            return;
            }
        }

    ManufacturingPricingAnalystSendQuotesJPanel manufacturingPricingAnalystSendQuotesJPanel =
     new ManufacturingPricingAnalystSendQuotesJPanel(
         userProcessContainer,
         userAccount,
         targetOrg,
         business
     );

    userProcessContainer.add("ManufacturingPricingAnalystSendQuotesJPanel", manufacturingPricingAnalystSendQuotesJPanel);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);

    }//GEN-LAST:event_btnSendQuotesActionPerformed

    private void btnRequestChangeProductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestChangeProductionActionPerformed
        // TODO add your handling code here:

        ProductionChangesJPanel productionChangesJPanel
        = new ProductionChangesJPanel(
            userProcessContainer,
            userAccount,
            organization,
            business,
                enterprise
        );

        userProcessContainer.add(
            "ProductionChangesJPanel",
            productionChangesJPanel
        );

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRequestChangeProductionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRequestChangeProduction;
    private javax.swing.JButton btnSendQuotes;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
