/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.RetailDataAnalystWorkArea;

import ui.StoreAssociateWorkArea.*;
import ui.StoreManagerWorkArea.*;
import ui.SupplierPricingAnalystRole.*;
import ui.SupplierPricingAnalystRole.*;
import Business.EcoSystem;
import Business.Organization.SupplierPricingOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ItemsRequest;
import Business.WorkQueue.ManufacturingQuotesRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class RetailDataAnalystFromManufacturer extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
     private Organization organization;
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public RetailDataAnalystFromManufacturer(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.organization = organization;  
        populateTable();
     
    }
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable1.getModel();
        model.setRowCount(0);

        for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof ItemsRequest) {
                ItemsRequest ir = (ItemsRequest) wr;
                Object[] row = new Object[4];
                row[0] = ir; // toString() = needItems
                row[1] = ir.getSender() == null ? null : ir.getSender().getEmployee().getName();
                row[2] = ir.getReceiver() == null ? null : ir.getReceiver().getEmployee().getName();
                row[3] = ir.getStatus();
                model.addRow(row);
            }
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refreshJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        workRequestJTable1 = new javax.swing.JTable();
        btnManuMakeRequest = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setText("Messages from Manufacturer");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        workRequestJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Receiver", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(workRequestJTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 540, 340));

        btnManuMakeRequest.setText("Make Request");
        btnManuMakeRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManuMakeRequestActionPerformed(evt);
            }
        });
        add(btnManuMakeRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
    populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void btnManuMakeRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManuMakeRequestActionPerformed
        // TODO add your handling code here:
    // Make Request to Manufacturer for more items

        String msg = JOptionPane.showInputDialog(
                this,
                "Enter request details for more items (e.g., item + quantity):",
                "Items Request",
                JOptionPane.PLAIN_MESSAGE
        );
        if (msg == null) {
            return; // cancelled
        }
        msg = msg.trim();
        if (msg.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a message.");
            return;
        }

        ItemsRequest request = new ItemsRequest();
        request.setMessage(msg);        // base WorkRequest message
        request.setTestResult(msg);     // your own field needItems
        request.setSender(userAccount);
        request.setStatus("Sent");

        // Add to Manufacturer org queue and sender's queue
        organization.getWorkQueue().getWorkRequestList().add(request);
        userAccount.getWorkQueue().getWorkRequestList().add(request);

        JOptionPane.showMessageDialog(this, "Request for items sent to Manufacturer.");
        populateTable();    
    }//GEN-LAST:event_btnManuMakeRequestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnManuMakeRequest;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JTable workRequestJTable1;
    // End of variables declaration//GEN-END:variables

    
}
