/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.StoreManagerWorkArea;

import Business.EcoSystem;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;



/**
 *
 * @author lajon
 */
public class StoreManagerMenuJPanel extends javax.swing.JPanel {
    private EcoSystem business;
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;

    /**
     * Creates new form StoreManagerMenuJPanel
     */
    
    public StoreManagerMenuJPanel() {
        this(null, null, null, null);
    }

    // Real constructor used from Role.createWorkArea(...)
    public StoreManagerMenuJPanel(JPanel userProcessContainer,
                                  UserAccount account,
                                  Organization organization,
                                  EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.business = business;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnStoreViewInventory = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Store Manager  Menu");

        btnStoreViewInventory.setBackground(new java.awt.Color(102, 153, 255));
        btnStoreViewInventory.setForeground(new java.awt.Color(255, 255, 255));
        btnStoreViewInventory.setText("View Inventory ");
        btnStoreViewInventory.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStoreViewInventory.setMaximumSize(new java.awt.Dimension(200, 40));
        btnStoreViewInventory.setMinimumSize(new java.awt.Dimension(20, 23));
        btnStoreViewInventory.setPreferredSize(new java.awt.Dimension(240, 30));
        btnStoreViewInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStoreViewInventoryIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btnStoreViewInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(btnStoreViewInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(329, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStoreViewInventoryIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStoreViewInventoryIdentifyResourceAssetsActionPerformed
       
        // TODO add your handling code here:
     if (userProcessContainer == null) {
            return;
        }

        StoreManagerWorkAreaJPanel workAreaPanel =
            new StoreManagerWorkAreaJPanel(
                userProcessContainer,
                userAccount,
                organization,
                business
            );

        userProcessContainer.add("StoreManagerWorkAreaJPanel", workAreaPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnStoreViewInventoryIdentifyResourceAssetsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStoreViewInventory;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
