/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.StoreManagerWorkArea;
import ui.StoreAssociateWorkArea.*;
import ui.RetailDataAnalystWorkArea.*;
import javax.swing.JPanel;
import java.awt.CardLayout;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.OrderModel.Product;
import Business.OrderModel.RetailerProductCatalog;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.StoreManagerToRetailBARestockRequest;
import Business.WorkQueue.WorkRequest;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author lajon
 */
public class StoreManagerInventoryJPanel extends javax.swing.JPanel {

   private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private EcoSystem business;
    private Enterprise enterprise;
    RetailerProductCatalog productCatalog;
    
     // Simple in-panel inventory: [productName, price, quantity]
    private List<Object[]> inventoryData = new ArrayList<>();

    /**
     * Creates new form RequestDataAnalystInventoryJPanel
     */
    public StoreManagerInventoryJPanel(JPanel userProcessContainer,
                                   UserAccount account,
                                   Organization organization,
                                   EcoSystem business,  Enterprise enterprise) {
    initComponents();
    this.userProcessContainer = userProcessContainer;
    this.userAccount = account;
    this.organization = organization;   
    this.business = business;
    this.productCatalog = business.getRetailerProductCatalog();
    this.enterprise = enterprise; 
        
     
        populateProductTable();
    }
    
      private void populateProductTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable1.getModel();
        model.setRowCount(0);
        for (Product p : productCatalog.getProductcatalog()){ 
            
                Object row[] = new Object[4];
                row[0] = p;
                row[1] = p.getModelNumber();
                row[2] = p.getPrice();
                row[3] = p.getAvail();
                model.addRow(row);
            
        }}
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        refreshJButton1 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnStoreRequestRestock = new javax.swing.JButton();

        workRequestJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product Name", "Product ID", "Price", "Availability"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable1);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setText("Store Inventory");

        refreshJButton1.setText("Refresh");
        refreshJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButton1ActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnStoreRequestRestock.setText("Request Restock");
        btnStoreRequestRestock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStoreRequestRestockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(415, 415, 415)
                                .addComponent(refreshJButton1))
                            .addComponent(btnStoreRequestRestock)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(refreshJButton1))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStoreRequestRestock)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButton1ActionPerformed
        // TODO add your handling code here:
        populateProductTable();
    }//GEN-LAST:event_refreshJButton1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnStoreRequestRestockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStoreRequestRestockActionPerformed
        // TODO add your handling code here:
    int selectedRow = workRequestJTable1.getSelectedRow();
    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(this, "Please select an item in the inventory table.");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) workRequestJTable1.getModel();
    Product product = (Product) model.getValueAt(selectedRow, 0);

    String qtyStr = JOptionPane.showInputDialog(
            this,
            "Enter quantity to request for item: " + product.getProdName(),
            "Request Restock",
            JOptionPane.PLAIN_MESSAGE
    );

    if (qtyStr == null) return; // user cancelled

    qtyStr = qtyStr.trim();
    if (qtyStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a quantity.");
        return;
    }

    int quantity;
    try {
        quantity = Integer.parseInt(qtyStr);
        if (quantity <= 0) {
            JOptionPane.showMessageDialog(this, "Quantity must be positive.");
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter a valid integer.");
        return;
    }

    String msg = "Request restock of " + product.getProdName() + " x " + quantity;

    StoreManagerToRetailBARestockRequest request = new StoreManagerToRetailBARestockRequest();
    request.setMessage(msg);
    request.setTestResult(msg); // if you're using this field
    request.setSender(userAccount);
    request.setStatus("Sent");

    Organization targetOrg = null;
    
    for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
        System.out.println("Checking org: " + org.getName());

        if (org.getName().equalsIgnoreCase("Retail Analytics Organization")) {
            targetOrg = org;
            break;
        }
    }
    if (targetOrg == null) {
        JOptionPane.showMessageDialog(this, "Retail Analytics Organization not found.");
        return;
    }


    targetOrg.getWorkQueue().getWorkRequestList().add(request);
    userAccount.getWorkQueue().getWorkRequestList().add(request);

    System.out.println("Request sent. Total in target org: " +
        targetOrg.getWorkQueue().getWorkRequestList().size()); // DEBUG

    JOptionPane.showMessageDialog(this, "Restock request sent successfully.");

 
    }//GEN-LAST:event_btnStoreRequestRestockActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnStoreRequestRestock;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshJButton1;
    private javax.swing.JTable workRequestJTable1;
    // End of variables declaration//GEN-END:variables
}
