/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.StoreManagerWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.ShippingFacilityOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.Network.Network;
import Business.Enterprise.Enterprise.EnterpriseType;
import Business.OrderModel.RetailerProductCatalog;
import Business.Organization.ShippingFacilityOrganization;


/**
 *
 * @author lajon
 */
public class StoreManagerMenuJPanel extends javax.swing.JPanel {
    private EcoSystem business;
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    RetailerProductCatalog productCatalog;
    /**
     * Creates new form StoreManagerMenuJPanel
     */
    
   

    // Real constructor used from Role.createWorkArea(...)
    public StoreManagerMenuJPanel(JPanel userProcessContainer,
                                  UserAccount account,
                                  Organization organization,
                                  Enterprise enterprise,
                                  EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnStoreViewInventory = new javax.swing.JButton();
        btnContactShippingCompany = new javax.swing.JButton();
        btnConfirmRequestsAssociates = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Store Manager  Menu");

        btnStoreViewInventory.setBackground(new java.awt.Color(102, 153, 255));
        btnStoreViewInventory.setForeground(new java.awt.Color(255, 255, 255));
        btnStoreViewInventory.setText("View Inventory ");
        btnStoreViewInventory.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStoreViewInventory.setMaximumSize(new java.awt.Dimension(200, 40));
        btnStoreViewInventory.setMinimumSize(new java.awt.Dimension(20, 23));
        btnStoreViewInventory.setPreferredSize(new java.awt.Dimension(240, 30));
        btnStoreViewInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStoreViewInventoryIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnContactShippingCompany.setBackground(new java.awt.Color(102, 153, 255));
        btnContactShippingCompany.setForeground(new java.awt.Color(255, 255, 255));
        btnContactShippingCompany.setText("Contact Shipping Company");
        btnContactShippingCompany.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnContactShippingCompany.setMaximumSize(new java.awt.Dimension(200, 40));
        btnContactShippingCompany.setMinimumSize(new java.awt.Dimension(20, 23));
        btnContactShippingCompany.setPreferredSize(new java.awt.Dimension(240, 30));
        btnContactShippingCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactShippingCompanyIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnConfirmRequestsAssociates.setBackground(new java.awt.Color(102, 153, 255));
        btnConfirmRequestsAssociates.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmRequestsAssociates.setText("Confirm Requests from Associates");
        btnConfirmRequestsAssociates.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConfirmRequestsAssociates.setMaximumSize(new java.awt.Dimension(200, 40));
        btnConfirmRequestsAssociates.setMinimumSize(new java.awt.Dimension(20, 23));
        btnConfirmRequestsAssociates.setPreferredSize(new java.awt.Dimension(240, 30));
        btnConfirmRequestsAssociates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmRequestsAssociatesIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnContactShippingCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnConfirmRequestsAssociates, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(btnStoreViewInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnContactShippingCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmRequestsAssociates, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btnStoreViewInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStoreViewInventoryIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStoreViewInventoryIdentifyResourceAssetsActionPerformed
       
        // TODO add your handling code here:
         if (userProcessContainer == null) {
            return;
        }

        StoreManagerInventoryJPanel storeManagerInventoryJPanel =
            new StoreManagerInventoryJPanel(
                userProcessContainer,
                userAccount,
                organization,
                business
            );

        userProcessContainer.add("StoreManagerInventoryJPanel", storeManagerInventoryJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
   
    }//GEN-LAST:event_btnStoreViewInventoryIdentifyResourceAssetsActionPerformed

    private void btnContactShippingCompanyIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactShippingCompanyIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
    // find the ShippingFacilityOrganization
    Organization shippingOrg = null;
    for (Organization org : /* shippingEnterprise */ enterprise.getOrganizationDirectory().getOrganizationList()) {
        if (org instanceof ShippingFacilityOrganization) {
            shippingOrg = org;
            break;
        }
    }
    if (shippingOrg == null) {
        JOptionPane.showMessageDialog(this, "No shipping organization found.");
        return;
    }

    ContactShippingWorkAreaJPanel1 panel =
        new ContactShippingWorkAreaJPanel1(userProcessContainer, userAccount, shippingOrg, business);
    userProcessContainer.add("ContactShippingWorkAreaJPanel1", panel);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);
    }//GEN-LAST:event_btnContactShippingCompanyIdentifyResourceAssetsActionPerformed

    private void btnConfirmRequestsAssociatesIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmRequestsAssociatesIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
          if (userProcessContainer == null) {
            return;
        }

        ContactStoreAssociateWorkAreaJPanel contactStoreAssociateWorkAreaJPanel =
            new ContactStoreAssociateWorkAreaJPanel(
                userProcessContainer,
                userAccount,
                organization,
                business
            );

        userProcessContainer.add("ContactStoreAssociateWorkAreaJPanel", contactStoreAssociateWorkAreaJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnConfirmRequestsAssociatesIdentifyResourceAssetsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmRequestsAssociates;
    private javax.swing.JButton btnContactShippingCompany;
    private javax.swing.JButton btnStoreViewInventory;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
