/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ShippingCoordinatorWorkArea;
import Business.EcoSystem;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
/**
 *
 * @author lajon
 */
public class ShippingCoordinatorMenuJPanel extends javax.swing.JPanel {
 private static final long serialVersionUID = 1L;

 private JPanel userProcessContainer;
 private UserAccount userAccount;
 private Organization organization;
 private EcoSystem business;
    /**
     * Creates new form ShippingCoordinatorMenuJPanel
     */
 public ShippingCoordinatorMenuJPanel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, EcoSystem business) {
 initComponents();
 this.userProcessContainer = userProcessContainer;
 this.userAccount = userAccount;
 this.organization = organization;
 this.business = business;
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnViewShipments = new javax.swing.JButton();
        btnConfirmRequestsSM = new javax.swing.JButton();
        btnConfirmRequestsPP = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Shipping Coordinator Menu");

        btnViewShipments.setBackground(new java.awt.Color(102, 153, 255));
        btnViewShipments.setForeground(new java.awt.Color(255, 255, 255));
        btnViewShipments.setText("View Shipments ");
        btnViewShipments.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewShipments.setMaximumSize(new java.awt.Dimension(200, 40));
        btnViewShipments.setMinimumSize(new java.awt.Dimension(20, 23));
        btnViewShipments.setPreferredSize(new java.awt.Dimension(240, 30));
        btnViewShipments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewShipmentsIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnConfirmRequestsSM.setBackground(new java.awt.Color(102, 153, 255));
        btnConfirmRequestsSM.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmRequestsSM.setText("Confirm Requests from Store Manager");
        btnConfirmRequestsSM.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConfirmRequestsSM.setMaximumSize(new java.awt.Dimension(200, 40));
        btnConfirmRequestsSM.setMinimumSize(new java.awt.Dimension(20, 20));
        btnConfirmRequestsSM.setPreferredSize(new java.awt.Dimension(240, 25));
        btnConfirmRequestsSM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmRequestsSMActionPerformed(evt);
            }
        });

        btnConfirmRequestsPP.setBackground(new java.awt.Color(102, 153, 255));
        btnConfirmRequestsPP.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmRequestsPP.setText("Confirm Requests from Production Planner");
        btnConfirmRequestsPP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConfirmRequestsPP.setMaximumSize(new java.awt.Dimension(200, 40));
        btnConfirmRequestsPP.setMinimumSize(new java.awt.Dimension(20, 20));
        btnConfirmRequestsPP.setPreferredSize(new java.awt.Dimension(240, 25));
        btnConfirmRequestsPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmRequestsPPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnConfirmRequestsPP, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnConfirmRequestsSM, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(btnViewShipments, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmRequestsSM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmRequestsPP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnViewShipments, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewShipmentsIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewShipmentsIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        if (userProcessContainer == null) {
            return;
        }

        ShippingCoordinatorWorkAreaJPanel shippingCoordinatorWorkAreaJPanel =
        new ShippingCoordinatorWorkAreaJPanel(
            userProcessContainer,
            userAccount,
            organization,
            business
        );

        userProcessContainer.add("ShippingCoordinatorWorkAreaJPanel", shippingCoordinatorWorkAreaJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewShipmentsIdentifyResourceAssetsActionPerformed

    private void btnConfirmRequestsSMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmRequestsSMActionPerformed
        // TODO add your handling code here:
         ShippingConfirmRequestsJPanel panel =
        new ShippingConfirmRequestsJPanel(
            userProcessContainer,
            userAccount,
            organization,
            business
        );

    userProcessContainer.add("ShippingConfirmRequestsJPanel", panel);

    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);
    }//GEN-LAST:event_btnConfirmRequestsSMActionPerformed

    private void btnConfirmRequestsPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmRequestsPPActionPerformed
        // TODO add your handling code here:
       ShippingConfirmProductionRequestsJPanel1 panel =
        new ShippingConfirmProductionRequestsJPanel1(
            userProcessContainer,
            userAccount,
            organization,
            business
        );

    userProcessContainer.add("ShippingConfirmProductionRequestsJPanel1", panel);

    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);
    }//GEN-LAST:event_btnConfirmRequestsPPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmRequestsPP;
    private javax.swing.JButton btnConfirmRequestsSM;
    private javax.swing.JButton btnViewShipments;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
