/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.RetailBusinessAnalystWorkArea;
import ui.SupplierPricingAnalystRole.SellSupplierProductsJPanel;
import Business.EcoSystem;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author lajon
 */
public class RetailerBusinessAnalystMenuJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private Organization organization;

    /**
     * Creates new form RetailerBusinessAnalystMenu
     */
    public RetailerBusinessAnalystMenuJPanel() {
        this(null, null, null, null);
    }

    // Real constructor used from Role.createWorkArea(...)
    public RetailerBusinessAnalystMenuJPanel(JPanel userProcessContainer,
                                       UserAccount account,
                                       Organization organization,
                                       EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.business = business;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRetailerBusinessViewInventory = new javax.swing.JButton();
        btnRetailerBusinessViewInventory2 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Retailer Business Analyst Menu");

        btnRetailerBusinessViewInventory.setBackground(new java.awt.Color(102, 153, 255));
        btnRetailerBusinessViewInventory.setForeground(new java.awt.Color(255, 255, 255));
        btnRetailerBusinessViewInventory.setText("Confirm Store Manager Requests");
        btnRetailerBusinessViewInventory.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRetailerBusinessViewInventory.setMaximumSize(new java.awt.Dimension(200, 40));
        btnRetailerBusinessViewInventory.setMinimumSize(new java.awt.Dimension(20, 23));
        btnRetailerBusinessViewInventory.setPreferredSize(new java.awt.Dimension(240, 30));
        btnRetailerBusinessViewInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetailerBusinessViewInventoryIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnRetailerBusinessViewInventory2.setBackground(new java.awt.Color(102, 153, 255));
        btnRetailerBusinessViewInventory2.setForeground(new java.awt.Color(255, 255, 255));
        btnRetailerBusinessViewInventory2.setText("View Sales Data");
        btnRetailerBusinessViewInventory2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRetailerBusinessViewInventory2.setMaximumSize(new java.awt.Dimension(200, 40));
        btnRetailerBusinessViewInventory2.setMinimumSize(new java.awt.Dimension(20, 23));
        btnRetailerBusinessViewInventory2.setPreferredSize(new java.awt.Dimension(240, 30));
        btnRetailerBusinessViewInventory2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetailerBusinessViewInventory2IdentifyResourceAssetsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnRetailerBusinessViewInventory2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(btnRetailerBusinessViewInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRetailerBusinessViewInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRetailerBusinessViewInventory2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(316, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetailerBusinessViewInventoryIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetailerBusinessViewInventoryIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
      if (userProcessContainer == null) {
            return;
        }

        RetailBusinessAnalystWorkAreaJPanel workAreaPanel =
            new RetailBusinessAnalystWorkAreaJPanel(
                userProcessContainer,
                userAccount,
                organization,
                business
            );

        userProcessContainer.add("RetailBusinessAnalystWorkAreaJPanel", workAreaPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnRetailerBusinessViewInventoryIdentifyResourceAssetsActionPerformed

    private void btnRetailerBusinessViewInventory2IdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetailerBusinessViewInventory2IdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetailerBusinessViewInventory2IdentifyResourceAssetsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRetailerBusinessViewInventory;
    private javax.swing.JButton btnRetailerBusinessViewInventory2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
