/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SupplierPricingAnalystRole;
import Business.EcoSystem;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;


/**
 *
 * @author lajon
 */
public class SupplierPricingAnalystMenuJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private Organization organization;
    /**
     * Creates new form SupplierMenuJPanel
     */
      public SupplierPricingAnalystMenuJPanel() {
        this(null, null, null, null);
    }

    public SupplierPricingAnalystMenuJPanel(JPanel userProcessContainer,
                                            UserAccount account,
                                            Organization organization,
                                            EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.business = business;
    }





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnViewInventory = new javax.swing.JButton();
        btnRequestMarketing = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Supplier Pricing Analyst Menu");

        btnViewInventory.setBackground(new java.awt.Color(102, 153, 255));
        btnViewInventory.setForeground(new java.awt.Color(255, 255, 255));
        btnViewInventory.setText("View Inventory ");
        btnViewInventory.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewInventory.setMaximumSize(new java.awt.Dimension(200, 40));
        btnViewInventory.setMinimumSize(new java.awt.Dimension(20, 23));
        btnViewInventory.setPreferredSize(new java.awt.Dimension(240, 30));
        btnViewInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewInventoryIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnRequestMarketing.setBackground(new java.awt.Color(102, 153, 255));
        btnRequestMarketing.setForeground(new java.awt.Color(255, 255, 255));
        btnRequestMarketing.setText("Request Marketing ");
        btnRequestMarketing.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRequestMarketing.setMaximumSize(new java.awt.Dimension(200, 40));
        btnRequestMarketing.setMinimumSize(new java.awt.Dimension(20, 20));
        btnRequestMarketing.setPreferredSize(new java.awt.Dimension(240, 25));
        btnRequestMarketing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestMarketingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnViewInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btnRequestMarketing, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRequestMarketing, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(320, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewInventoryIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewInventoryIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
 if (userProcessContainer == null) {
            return;
        }

        SupplierPricingAnalystInventoryJPanel supplierPricingAnalystInventoryJPanel =
            new SupplierPricingAnalystInventoryJPanel(
                userProcessContainer,
                userAccount,
                organization,
                business
            );

        userProcessContainer.add("SupplierPricingAnalystInventoryJPanel", supplierPricingAnalystInventoryJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnViewInventoryIdentifyResourceAssetsActionPerformed

    private void btnRequestMarketingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestMarketingActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btnRequestMarketingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRequestMarketing;
    private javax.swing.JButton btnViewInventory;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
